server:
  port: 2332

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: orangecloud-api-dev
---
spring:
  profiles: test
  application:
    name: orangecloud-api-test

